# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loaderVersionRange}" #mandatory (24 is current forge version)
# License
license="\"Don't Be a Jerk\" non-commercial care-free license" #mandatory
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/${githubUrl}/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="betteradvancements" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory
 # A display name for the mod
displayName="Better Advancements" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="${curseHomepageLink}" #optional
# A text field displayed in the mod UI
authors="${modAuthor}" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Improvements to the advancements screen.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.betteradvancements]]
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forgeVersionRange}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="CLIENT"

[[dependencies.betteradvancements]]
modId="minecraft" #mandatory
mandatory=true #mandatory
versionRange="${minecraftVersionRange}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="CLIENT"